server:
  port: 8001
datasoure:
  host: 47.107.140.71
  port: 3306
  username: aliyunget
  password: yuan@get940314
  database: test
  charset: utf8
Upload:
  img: D:\Go\projiect\src\go-gin-admin\upload\img\
  tmp: D:\Go\projiect\src\go-gin-admin\upload\tmp\
Jwt:
  key: SE@13W#@#SD123SA